// A curated list of common gym exercises for the search picker in Build.
// This is separate from Store.exercises (the user's own saved exercise
// definitions) — picking one of these creates a Store entry on first use.
export const EXERCISE_DB = [
  // Chest
  { name: "Barbell Bench Press", category: "Chest" },
  { name: "Incline Barbell Bench Press", category: "Chest" },
  { name: "Decline Barbell Bench Press", category: "Chest" },
  { name: "Dumbbell Bench Press", category: "Chest" },
  { name: "Incline Dumbbell Press", category: "Chest" },
  { name: "Dumbbell Fly", category: "Chest" },
  { name: "Cable Fly", category: "Chest" },
  { name: "Chest Dip", category: "Chest" },
  { name: "Push-Up", category: "Chest" },
  { name: "Machine Chest Press", category: "Chest" },
  { name: "Pec Deck", category: "Chest" },
  { name: "Landmine Press", category: "Chest" },

  // Back
  { name: "Deadlift", category: "Back" },
  { name: "Sumo Deadlift", category: "Back" },
  { name: "Barbell Row", category: "Back" },
  { name: "Pendlay Row", category: "Back" },
  { name: "Dumbbell Row", category: "Back" },
  { name: "T-Bar Row", category: "Back" },
  { name: "Seated Cable Row", category: "Back" },
  { name: "Lat Pulldown", category: "Back" },
  { name: "Pull-Up", category: "Back" },
  { name: "Chin-Up", category: "Back" },
  { name: "Face Pull", category: "Back" },
  { name: "Straight-Arm Pulldown", category: "Back" },
  { name: "Good Morning", category: "Back" },
  { name: "Hyperextension", category: "Back" },
  { name: "Rack Pull", category: "Back" },

  // Legs
  { name: "Back Squat", category: "Legs" },
  { name: "Front Squat", category: "Legs" },
  { name: "Goblet Squat", category: "Legs" },
  { name: "Hack Squat", category: "Legs" },
  { name: "Leg Press", category: "Legs" },
  { name: "Romanian Deadlift", category: "Legs" },
  { name: "Stiff-Leg Deadlift", category: "Legs" },
  { name: "Walking Lunge", category: "Legs" },
  { name: "Reverse Lunge", category: "Legs" },
  { name: "Bulgarian Split Squat", category: "Legs" },
  { name: "Leg Extension", category: "Legs" },
  { name: "Leg Curl", category: "Legs" },
  { name: "Hip Thrust", category: "Legs" },
  { name: "Glute Bridge", category: "Legs" },
  { name: "Standing Calf Raise", category: "Legs" },
  { name: "Seated Calf Raise", category: "Legs" },
  { name: "Hip Abduction", category: "Legs" },
  { name: "Hip Adduction", category: "Legs" },

  // Shoulders
  { name: "Overhead Press", category: "Shoulders" },
  { name: "Seated Dumbbell Press", category: "Shoulders" },
  { name: "Arnold Press", category: "Shoulders" },
  { name: "Lateral Raise", category: "Shoulders" },
  { name: "Cable Lateral Raise", category: "Shoulders" },
  { name: "Front Raise", category: "Shoulders" },
  { name: "Rear Delt Fly", category: "Shoulders" },
  { name: "Upright Row", category: "Shoulders" },
  { name: "Barbell Shrug", category: "Shoulders" },
  { name: "Dumbbell Shrug", category: "Shoulders" },

  // Arms
  { name: "Barbell Curl", category: "Arms" },
  { name: "Dumbbell Curl", category: "Arms" },
  { name: "Hammer Curl", category: "Arms" },
  { name: "Preacher Curl", category: "Arms" },
  { name: "Concentration Curl", category: "Arms" },
  { name: "Cable Curl", category: "Arms" },
  { name: "Tricep Pushdown", category: "Arms" },
  { name: "Overhead Tricep Extension", category: "Arms" },
  { name: "Skull Crusher", category: "Arms" },
  { name: "Close-Grip Bench Press", category: "Arms" },
  { name: "Bench Dip", category: "Arms" },

  // Core
  { name: "Plank", category: "Core" },
  { name: "Side Plank", category: "Core" },
  { name: "Crunch", category: "Core" },
  { name: "Sit-Up", category: "Core" },
  { name: "Hanging Leg Raise", category: "Core" },
  { name: "Cable Crunch", category: "Core" },
  { name: "Russian Twist", category: "Core" },
  { name: "Ab Wheel Rollout", category: "Core" },
  { name: "Mountain Climber", category: "Core" },
  { name: "Bicycle Crunch", category: "Core" },
  { name: "Woodchopper", category: "Core" },

  // Olympic / Power
  { name: "Power Clean", category: "Olympic" },
  { name: "Clean and Jerk", category: "Olympic" },
  { name: "Snatch", category: "Olympic" },
  { name: "Push Press", category: "Olympic" },
  { name: "Box Jump", category: "Olympic" },
  { name: "Kettlebell Swing", category: "Olympic" },
  { name: "Farmer's Carry", category: "Olympic" },

  // Cardio
  { name: "Treadmill Run", category: "Cardio" },
  { name: "Rowing Machine", category: "Cardio" },
  { name: "Stationary Bike", category: "Cardio" },
  { name: "Jump Rope", category: "Cardio" },
  { name: "Elliptical", category: "Cardio" },
  { name: "Stair Climber", category: "Cardio" },
  { name: "Burpee", category: "Cardio" },
];
